### ISSUE TITLE
isPointInPath usage

### ISSUE THREAD

**Issue by baetheus** [gcanti/graphics-ts#8]
Drawing with graphics-ts is great! However, I have a use case where I need to handle clicks and check if they are contained in a closed Shape. It looks like the Canvas part of the library includes a method for checking if a point is in a path, but I'm failing to see how to watch for events that land coordinates in a path.

Right now I'm considering writing a Closed Path to Canvas Path combinator and using isPointInPath to manually check for a click imperatively. Any advice would be super helpful. Thanks!

**Comment by IMax153** [comment]
Hey @baetheus! I am really glad you are enjoying `graphics-ts`!

One method that you could consider for checking if a clicked coordinate lands in a particular path is to use the `bind` function from the `Canvas` module to bind a click handler to the `<canvas />` element.

We can modify the signature of `bind` slightly to use the `canvas` property on the `CanvasRenderingContext2D` to add our event listener. This will allow us to easily pipe `bind` in the `Render` context instead of being forced to work with it in the `Html` context.

```typescript
import * as C from 'graphics-ts/lib/Canvas'

const bind = <K extends keyof HTMLElementEventMap, A>(
  type: K,
  f: (e: HTMLElementEventMap[K]) => C.Render<A>
): C.Render<CanvasRenderingContext2D> => (ctx) => () => {
  ctx.canvas.addEventListener(type, (e) => f(e)(ctx)());
  return ctx;
}
```

`graphics-ts` has a built in function named `renderShape` in the `Drawing` module that is used to lift `Shape`s into the `Render` context. However, at the moment it is not exported. Given its application to your problem, we can certainly consider exporting it from the `Drawing` module. 

For now though, let's just extract the portion for drawing a `Path`.

```typescript
import * as IO from 'fp-ts/lib/IO'
import * as RA from 'fp-ts/lib/ReadonlyArray'
import * as R from 'fp-ts-contrib/lib/ReaderIO'
import * as S from 'graphics-ts/lib/Shape'

const renderPath = (path: S.Path): C.Render<CanvasRenderingContext2D> =>
  pipe(
    path.points,
    RA.foldLeft(
      () => IO.of,
      (head, tail) =>
        pipe(
          C.moveTo(head),
          R.chain(() => RA.readonlyArray.traverse(R.readerIO)(tail, C.lineTo)),
          R.chain(() => (path.closed ? C.closePath : IO.of))
        )
    )
  )
```

Now we can create our event handler. This function first checks if the clicked coordinates are in the current `Path` and executes an `eff` if it is. I passed the `MouseEvent` to the `eff` function to give us access to the event properties later.

```typescript
const onMouseClick = (eff: (e: MouseEvent) => IO.IO<void>) => (
  e: MouseEvent
): C.Render<void> =>
  pipe(
    C.isPointInPath(S.point(e.offsetX, e.offsetY)),
    R.chain((pointInPath) =>
      pointInPath ? R.fromIO(eff(e)) : IO.of
    )
  )
```

And finally we can put it all together to bind our event handler to the `<canvas />` element.

```html
<canvas id="canvas-1" height="600" width="800" />
```

```typescript
import { error } from 'fp-ts/lib/Console'

const canvasId = "canvas-1"

const closedPath = S.closed(RA.readonlyArray)

const onCanvasNotFound = (): IO.IO<void> =>
  error(`[ERROR]: Unable to find canvas element with id ${canvasId}`);

const path: C.Render<CanvasRenderingContext2D> = renderPath(
  closedPath([S.point(20, 140), S.point(120, 10), S.point(220, 140)])
)

const onClick: C.Render<CanvasRenderingContext2D> = bind(
  "click",
  onMouseClick((e) => IO.of(alert(`In path: (${e.offsetX}, ${e.offsetY})`)))
)

C.renderTo(canvasId, onCanvasNotFound)(
  C.strokePath(
    pipe(
      path,
      R.chain(() => onClick)
    )
  )
)()
```

To reduce the verbosity of addressing situations such as this, we should probably consider exporting `renderShape` from `Drawing.ts`. In addition, there may be a better way of handling the competing `Html` and `Render` contexts when `bind`ing event handlers. @gcanti - Do you have any suggestions?
